server:
  port: 8000

spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: haha
            preLogger: true
            postLogger: true

      routes:
        - id: first-service
          uri: http://localhost:8001
          predicates:
            - Path=/first-service/**
          filters:
            - AddRequestHeader=first-req, first-req-val
            - AddResponseHeader=first-resp, first-resp-val
            - CustomFilter
        - id: second-service
          uri: http://localhost:8002
          predicates:
            - Path=/second-service/**
          filters:
            - AddRequestHeader=second-req, second-req-val
            - AddResponseHeader=second-resp, second-resp-val
            - CustomFilter
            - name : LoggingFilter
