server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: haha
            preLogger: true
            postLogger: true

      routes:
        - id: first-service
#          uri: http://localhost:8001
          uri: lb://MY-FIRST-SERVICE
          predicates:
            - Path=/first-service/**
          filters:
            - AddRequestHeader=first-req, first-req-val
            - AddResponseHeader=first-resp, first-resp-val
            - CustomFilter
        - id: second-service
#          uri: http://localhost:8002
          uri: lb://MY-SECOND-SERVICE
          predicates:
            - Path=/second-service/**
          filters:
            - AddRequestHeader=second-req, second-req-val
            - AddResponseHeader=second-resp, second-resp-val
            - CustomFilter
            - name : LoggingFilter
